[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "siky-hfd" 
version = "0.1.1" 
description = "从 Hugging Face 或 ModelScope 使用提供的 repo ID 下载模型或数据集。"
readme = "README.md"
license = "MIT" 
authors = [
    { name = "siky", email = "siky47@outlook.com" }, 
]
requires-python = ">=3.8" 
# 外部依赖
# dependencies = [
#     "requests",
# ]

# 定义命令行入口点
[project.scripts]
hfd = "hfd.cli:run" # 安装后，hfd 命令将执行 hfd.cli模块中的 run 函数

[project.urls]
Homepage = "https://github.com/SevenFo/huggingface-downloader"
Repository = "https://github.com/SevenFo/huggingface-downloader"
PyPI = "https://pypi.org/project/siky-hfd/"

[project.optional-dependencies]
dev = [
    "pytest>=7.0",      # 测试框架
    "pytest-mock>=3.0", # 用于模拟对象
    "build",            # 用于构建包
    # "ruff",           # 可选：代码格式化和 Linting
    # "mypy",           # 可选：静态类型检查
]

[tool.hatch.build.targets.wheel]
packages = ["src/hfd"]