name: Publish Python Package to TestPyPI

on:
  push:
    tags:
      - 'test_v*' # 只在 test_v* 标签时触发

jobs:
  deploy-test:
    runs-on: ubuntu-latest
    environment:
      name: pypitest
      url: https://test.pypi.org/p/siky-hfd
    permissions:
      contents: write # 需要 write 权限来创建 Release 和上传文件

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build

    - name: Publish package to TestPyPI
      # 只发布到 TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        # 使用 TestPyPI 的 API Token
        password: ${{ secrets.PYPI_API_TOKEN }} 
        repository-url: https://test.pypi.org/legacy/ 

    - name: Create GitHub Release for Test Tag
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you don't need to create it
      with:
        tag_name: ${{ github.ref_name }} # 使用触发工作流的标签名
        release_name: Draft Release ${{ github.ref_name }} (TestPyPI)
        body: |
          Test release draft for ${{ github.ref_name }}. Published to TestPyPI.
        draft: true
        prerelease: false

    - name: Get asset names
      id: get_asset_names
      run: |
        echo "WHL_PATH=$(ls dist/*.whl | head -n 1)" >> $GITHUB_ENV
        echo "SDIST_PATH=$(ls dist/*.tar.gz | head -n 1)" >> $GITHUB_ENV
        echo "WHL_NAME=$(basename $(ls dist/*.whl | head -n 1))" >> $GITHUB_ENV
        echo "SDIST_NAME=$(basename $(ls dist/*.tar.gz | head -n 1))" >> $GITHUB_ENV

    - name: Upload Release Assets (Wheel)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # 从上一步获取上传 URL
        asset_path: ${{ env.WHL_PATH }}
        asset_name: ${{ env.WHL_NAME }}
        asset_content_type: application/zip

    - name: Upload Release Assets (sdist)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # 从上一步获取上传 URL
        asset_path: ${{ env.SDIST_PATH }}
        asset_name: ${{ env.SDIST_NAME }}
        asset_content_type: application/gzip
